server:
  port: 8080

springdoc:
  packages-to-scan: kg.core
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    doc-expansion: none

spring:
  profiles:
    active: minio

  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            issuer-uri: https://accounts.google.com

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: core

security:
  jwt:
    secret: "1ewj+l/KMCUOpR4HH98V2fRtozeFm/VU2tNTze+w8i4="
    access-token-expiration-ms: 900000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.flywaydb: debug
